// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Invoice { invoice_number: string, date: string, name: string, company: string, total: number, currency: string, file: string, }